<?php defined("BP_START") || die("Unauthorized Access");
$content = array (
  'unpublished' => '',
  'theme' => 'basic',
  'style' => 'blue-grey.css',
  'lastmod' => '2013-11-16T23:57:33-07:00',
  'nav' => 1,
  'sitemap' => 1,
  'keywords' => '',
  'description' => '',
  'published' => '<h1>Downloads</h1><h1><div style="color: rgb(0, 0, 0); font-weight: normal;"><div><hr></div></div></h1><h3>Symbulator 6</h3><h1><div style="color: rgb(0, 0, 0);"><ul><li><i style="font-weight: normal;">Software</i></li><ul style="font-weight: normal;"><li><a href="https://www.dropbox.com/s/su4so72m83l214w/s.zip"><b>Beta Release</b></a>&nbsp;(Revised Aug 11, 2013)&nbsp;</li></ul><li><i style="font-weight: normal;">Documentation</i></li><ul><li><a href="https://www.dropbox.com/s/tjau1p7ap9y5io5/Part-1.pdf">Part 1: DC</a><span style="font-weight: normal;">&nbsp;(Finished.&nbsp;Aug 14, 2013.&nbsp;26MB, 165 examples, 86 p.)</span></li><li><span style="font-weight: normal;"><a href="https://www.dropbox.com/s/cvfbjynurq1o2gl/Part-2.pdf">Part 2: TR</a> (In progress.&nbsp;Nov 17, 2013.&nbsp;&lt;2MB, 31 examples. 22 p.)</span></li><li><span style="font-weight: normal;">Part 3: AC (Coming later)</span></li><li><span style="font-weight: normal;">Part 4: FD&nbsp;(Coming later)</span></li></ul></ul><div style="font-weight: normal;"><hr></div></div></h1><h3>Symbulator 5</h3><h1><div style="color: rgb(0, 0, 0);"><ul><li><span style="font-weight: normal;"><i>Software</i></span></li><ul><li><span style="font-weight: normal;"><a href="https://www.dropbox.com/s/lxv1yvh2jehiuiw/sq.89g">Final Release</a>&nbsp;(Updated on April 16, 2003)</span></li></ul><li><span style="font-weight: normal;"><i>Documentation</i><br></span></li><ul><li><span style="font-weight: normal;"><a href="https://www.google.com/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=1&amp;cad=rja&amp;ved=0CC0QFjAA&amp;url=http%3A%2F%2Fwww.mit.edu%2F~roberto%2Fdocs%2Fbsc.pdf&amp;ei=K9DtUem7LsW64AOL_YEQ&amp;usg=AFQjCNFmFPO7XaLu2xVAwP89utXXsXdWGA&amp;sig2=sdp5BxgR3ZCXxKf-Ok3_BQ&amp;bvm=bv.49478099,d.dmg">Thesis</a>&nbsp;(In Spanish. Completed in 2001.)<br></span></li><li><span style="font-weight: normal;"><a href="http://perez-franco.com/symbulator/frontpage/index.html">Website</a>&nbsp;(Partial, last updated in 2000.)</span></li></ul></ul><div style="font-weight: normal;"><hr></div></div></h1><h3>DiffEq</h3><h1><div style="color: rgb(0, 0, 0); font-weight: normal;"><ul><li>For Laplace transforms, Symbulator relies on Lars Frederiksen\'s DiffEq. Get it&nbsp;<a href="https://www.dropbox.com/s/d956pmo97ovwziu/d.zip">here</a>.</li></ul></div></h1><h1><div style="color: rgb(0, 0, 0);"><div style="font-weight: normal;"><hr></div></div></h1><h3>Other programs</h3><h1><div style="color: rgb(0, 0, 0); font-weight: normal;"><div></div></div></h1><h1><div style="color: rgb(0, 0, 0); font-weight: normal;"><ul><li>Some other useful programs, hosted at request of their authors, can be found&nbsp;<a href="http://perez-franco.com/symbulator/download/index.html">here</a>.</li></ul></div></h1>
',
);