"""Measure every figure scan and write tools/figure_sizes.json (#153).

The problem this solves: the figures are scans cropped from a dozen
textbooks and resampled to arbitrary pixel sizes (most practice scans were
normalised to 1100 px wide by the 2023 site conversion), so neither pixel
width nor DPI metadata says how large a figure should print.  What should
be constant across the book is the size of the text *inside* a figure: a
figure is correctly sized when its labels match the body text (Roberto,
29 Aug 2026).

For each image this script estimates the label text height in pixels:
grayscale -> threshold (Otsu, capped at 140 so the beige Bo2 scans do not
weld into blobs) -> horizontal dilation to merge characters into words ->
connected components -> keep word-shaped components -> median height, with
a guard against the swarm of 8-11 px dash segments that dashed boxes and
mesh arrows produce.

build.py then renders each figure at
    width = image_px_width * TARGET_MM / text_px    (capped at the line)
so label text lands at TARGET_MM in print, and at the same proportion of
the column on the web.

The output JSON also carries an "overrides" block, preserved across
re-runs: set a width in millimetres there for any figure the detector gets
wrong, and build.py uses it verbatim.

Run from Documentation/:  python tools/measure_figures.py
"""
import json
import os
import sys

import numpy as np
from PIL import Image
from scipy import ndimage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
OUT = os.path.join(ROOT, "tools", "figure_sizes.json")

TARGET_MM = 2.7      # label text height in print; body text is 11pt Plex
LINE_MM = 156.0      # A4 text block: 210 - 24 - 30


def otsu(gray: np.ndarray) -> int:
    hist, _ = np.histogram(gray, bins=256, range=(0, 255))
    total = gray.size
    sum_all = float(np.dot(np.arange(256), hist))
    sum_b = 0.0
    w_b = 0
    best, thresh = 0.0, 127
    for t in range(256):
        w_b += int(hist[t])
        if w_b == 0:
            continue
        w_f = total - w_b
        if w_f == 0:
            break
        sum_b += t * int(hist[t])
        m_b = sum_b / w_b
        m_f = (sum_all - sum_b) / w_f
        var = w_b * w_f * (m_b - m_f) ** 2
        if var > best:
            best, thresh = var, t
    return thresh


def measure(path):
    """Return (w_px, h_px, text_px, n_words); text_px 0 = no estimate."""
    img = Image.open(path).convert("L")
    gray = np.asarray(img, dtype=np.uint8)
    h, w = gray.shape
    t = min(otsu(gray), 140)
    dark = gray < t
    if dark.mean() > 0.5:
        dark = ~dark
    words = ndimage.binary_dilation(dark, structure=np.ones((1, 9), bool))
    labels, n = ndimage.label(words)
    if n == 0:
        return (w, h, 0.0, 0)
    heights = []
    for s in ndimage.find_objects(labels):
        ch = s[0].stop - s[0].start
        cw = s[1].stop - s[1].start
        if not (8 <= ch <= 90):
            continue
        if cw < 0.7 * ch or cw > 8.0 * ch:   # wires, dash rows: line-thin
            continue
        if cw > 0.35 * w:                    # artwork, not a word
            continue
        ink = dark[s].mean()
        if ink < 0.08 or ink > 0.95:
            continue
        heights.append(ch)
    if not heights:
        return (w, h, 0.0, 0)
    big = [x for x in heights if x >= 13]
    pop = big if len(big) >= 5 else heights
    return (w, h, float(np.median(pop)), len(heights))


def main():
    overrides = {}
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as fh:
            overrides = json.load(fh).get("overrides", {})
    measured = {}
    failures = []
    for root, _dirs, files in os.walk(ASSETS):
        for f in sorted(files):
            if not f.lower().endswith((".png", ".jpg", ".jpeg")):
                continue
            p = os.path.join(root, f)
            rel = os.path.relpath(p, ASSETS).replace("\\", "/")
            try:
                w, h, tpx, nw = measure(p)
            except Exception as e:       # unreadable file: leave it out
                print(f"measure_figures: FAILED on {rel}: {e}", file=sys.stderr)
                continue
            measured[rel] = {"w": w, "h": h, "text_px": tpx, "n_words": nw}
            if tpx <= 0 and rel not in overrides:
                failures.append(rel)
    doc = {
        "_comment": "Generated by tools/measure_figures.py; see its "
                    "docstring. Edit only 'overrides' (width in mm), "
                    "which re-runs preserve.",
        "target_mm": TARGET_MM,
        "line_mm": LINE_MM,
        "overrides": overrides,
        "measured": measured,
    }
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(doc, fh, indent=1, sort_keys=True)
        fh.write("\n")
    print(f"measure_figures: {len(measured)} measured -> {OUT}")
    if failures:
        print("measure_figures: no text estimate (add an override or "
              "build.py falls back to 72% of the line):")
        for rel in failures:
            print("  ", rel)


if __name__ == "__main__":
    main()
