"""A Baker's Dozen as LaTeX: writes bakers_dozen.tex beside this file.

    py paper\\bakers_dozen\\build_dozen_tex.py            write the .tex
    py paper\\bakers_dozen\\build_dozen_tex.py --pdf      and compile it

Roberto, 17 Sep 2026: a LaTeX version of the booklet, for the public
repository. The published PDF (learn.symbulator.com/dozen.pdf) is still the
one build_dozen.py prints through Edge. This writes the same content from
the same data, P and BONUS in build_dozen.py, so the two cannot disagree
about a question, a description or an answer. Edit the data there, never
the generated .tex.

The .tex compiles with XeLaTeX and needs IBM Plex (Sans, Serif and Mono)
installed, DejaVu Sans Mono (it ships with TeX distributions), and the
packages named in its preamble. Plex Serif and Plex Mono have no Greek and
no angle sign, so those characters are mapped with newunicodechar. The
figures are read from Documentation/assets/, relative to the .tex, and
AS7 Problem 19.2's ladder is drawn with circuitikz.
"""
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import build_dozen as B  # noqa: E402

OUT = os.path.join(HERE, "bakers_dozen.tex")
ASSETS_REL = "../../assets/"          # from this folder to Documentation/assets
LOGO_REL = "../../web/assets/logo.png"
PX_MM = 25.4 / 96                     # the HTML booklet's CSS pixel
MAX_H_MM = 62

TEXT_ESC = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
            "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
            "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def esc(s):
    return "".join(TEXT_ESC.get(c, c) for c in s)


def prose(s):
    """Escape text, keeping $...$ maths as maths."""
    parts = re.split(r"(\$[^$]*\$)", s)
    return "".join(p if p.startswith("$") and p.endswith("$") and len(p) > 1
                   else esc(p) for p in parts)


def figure(img):
    if img.startswith("SVG:"):
        return LADDER
    path = os.path.join(B.ASSETS, img)
    w, h = Image.open(path).size
    w_mm, h_mm = w * PX_MM, h * PX_MM
    scale = min(1.0, MAX_H_MM / h_mm)
    return (r"\begin{center}\includegraphics[width=%.1fmm,max width=\linewidth]{%s}"
            r"\end{center}" % (w_mm * scale, ASSETS_REL + img))


# AS7 Problem 19.2: four 1 ohm resistors in each rail, three 1 ohm rungs.
LADDER = r"""\begin{center}
\begin{circuitikz}[scale=0.85, transform shape, american]
\draw (0,3) node[ocirc, label=left:\textcolor{accent}{a}]{}
  to[R=1\,$\Omega$, -*] (2.5,3) node[above right, text=accent]{b}
  to[R=1\,$\Omega$, -*] (5,3)   node[above right, text=accent]{c}
  to[R=1\,$\Omega$, -*] (7.5,3) node[above right, text=accent]{d}
  to[R=1\,$\Omega$, -o] (10,3)  node[right, text=accent]{e};
\draw (0,0) node[ocirc, label=left:\textcolor{accent}{f}]{}
  to[R, l_=1\,$\Omega$, -*] (2.5,0) node[below right, text=accent]{g}
  to[R, l_=1\,$\Omega$, -*] (5,0)   node[below right, text=accent]{h}
  to[R, l_=1\,$\Omega$, -*] (7.5,0) node[below right, text=accent]{i}
  to[R, l_=1\,$\Omega$, -o] (10,0)  node[right, text=accent]{j};
\draw (2.5,3) to[R=1\,$\Omega$] (2.5,0);
\draw (5,3)   to[R=1\,$\Omega$] (5,0);
\draw (7.5,3) to[R=1\,$\Omega$] (7.5,0);
\end{circuitikz}
\end{center}"""

PREAMBLE = r"""% A Baker's Dozen -- twelve solved examples from Symbulator 9's
% documentation, and a bonus. GENERATED by build_dozen_tex.py from the data
% in build_dozen.py; edit that, not this. Compile with XeLaTeX.
\documentclass[10pt]{article}
\usepackage[a4paper,top=16mm,bottom=16mm,left=17mm,right=17mm]{geometry}
\usepackage{fontspec}
\setmainfont{IBM Plex Serif}
\setsansfont{IBM Plex Sans}
\setmonofont{IBM Plex Mono}[Scale=0.88]
\newfontfamily\anglefont{DejaVuSansMono.ttf}[Scale=0.88]
\usepackage{amsmath,amssymb}
\usepackage{newunicodechar}
\newunicodechar{Ω}{\ensuremath{\Omega}}
\newunicodechar{ω}{\ensuremath{\omega}}
\newunicodechar{Δ}{\ensuremath{\Delta}}
\newunicodechar{∠}{{\anglefont ∠}}
\usepackage[table]{xcolor}
\definecolor{navy}{HTML}{203864}
\definecolor{accent}{HTML}{2F5FA8}
\definecolor{accentbg}{HTML}{E9EFF8}
\definecolor{ink2}{HTML}{545D6D}
\definecolor{ink3}{HTML}{858D9C}
\definecolor{rule}{HTML}{E2E5EA}
\definecolor{answer}{HTML}{A13030}
\definecolor{gold}{HTML}{D9A521}
\definecolor{lcd}{HTML}{F2F6FC}
\definecolor{lcdedge}{HTML}{DBE4F2}
\usepackage{graphicx}
\usepackage[export]{adjustbox}
\usepackage{fancyvrb}
\usepackage[most]{tcolorbox}
\usepackage[siunitx]{circuitikz}
\usepackage{array}
\usepackage[hidelinks]{hyperref}
\urlstyle{tt}
\frenchspacing
\setlength{\parindent}{0pt}
\setlength{\parskip}{0pt}
\pagestyle{empty}

\newtcolorbox{whybox}{enhanced, breakable, colback=accentbg, boxrule=0pt,
  leftrule=1.1mm, colframe=accent, arc=0pt, outer arc=0pt,
  left=3mm, right=3mm, top=2mm, bottom=2mm, before skip=1mm, after skip=3mm}
\newtcolorbox{codebox}{colback=lcd, colframe=lcdedge, boxrule=0.4pt, arc=1.2mm,
  left=2.5mm, right=2.5mm, top=1.5mm, bottom=1.5mm, before skip=0.8mm, after skip=1.4mm}
\newtcolorbox{answerbox}{colback=white, colframe=answer, boxrule=0pt,
  leftrule=0.6mm, arc=0pt, outer arc=0pt, left=2.5mm, right=0mm, top=0.4mm,
  bottom=0.4mm, before skip=0.9mm, after skip=0.9mm, fontupper=\color{answer}}

\newcommand{\kicker}[1]{{\setlength{\fboxsep}{1.2mm}\colorbox{navy}{%
  \textcolor{white}{\sffamily\scriptsize\addfontfeature{LetterSpace=18}\MakeUppercase{#1}}}}}
% Not uppercased: a label like "TR, t > 0" carries a variable.
\newcommand{\runhead}[1]{{\sffamily\footnotesize\bfseries\color{accent}#1}\par\vspace{0.6mm}}
\newcommand{\settings}[1]{{\sffamily\footnotesize\color{ink2}#1}\par}
\newcommand{\applink}[1]{\vspace{0.6mm}{\scriptsize\color{accent}\url{#1}}\par}

\newenvironment{problem}[4]{%
  \newpage
  \kicker{#1}\par\vspace{2.5mm}
  {\sffamily\fontsize{20}{24}\selectfont\bfseries\color{navy}#2\par}
  \vspace{0.8mm}{\sffamily\large\color{accent}#3\par}
  \vspace{0.8mm}{\sffamily\footnotesize\color{ink3}#4\par}
  \vspace{1.5mm}{\color{gold}\rule{\linewidth}{0.7pt}}\par\vspace{3mm}
}{}

\begin{document}
"""


def run_block(label, book, n, key, settings, results):
    link = f"{B.APP}?lesson={key}&entry={n}"
    lines = [r"\runhead{%s}" % esc(label),
             r"\begin{codebox}", r"\begin{Verbatim}[fontsize=\small]",
             B.entry(book, n), r"\end{Verbatim}", r"\end{codebox}",
             r"\settings{%s}" % esc(settings)]
    for r in results:
        # max width shrinks only an answer too wide for its column (Boulet's).
        lines += [r"\begin{answerbox}",
                  r"\adjustbox{max width=\linewidth}{$\displaystyle %s$}" % r,
                  r"\end{answerbox}"]
    lines.append(r"\applink{%s}" % link)
    return "\n".join(lines)


def problem(p, label):
    out = [r"\begin{problem}{%s}{%s}{%s}{%s}" % (esc(label), esc(p["title"]),
                                                 esc(p["tag"]), esc(p["where"])),
           r"{\itshape %s\par}" % prose(p["question"]),
           r"\vspace{1mm}", figure(p["img"]),
           r"\begin{whybox}\textbf{\sffamily\color{navy}Why it is here.} %s\end{whybox}"
           % esc(p["why"])]
    runs = p["runs"]
    if len(runs) == 1:
        out.append(run_block(*runs[0]))
    else:
        cols = [r"\begin{minipage}[t]{0.485\linewidth}" + "\n" + run_block(*r)
                + "\n" + r"\end{minipage}" for r in runs]
        out.append("\\hfill\n".join(cols))
    out.append(r"\end{problem}")
    return "\n".join(out)


def cover():
    rows = []
    for i, p in enumerate(B.P, 1):
        rows.append(r"\textcolor{accent}{\bfseries %d} & \textbf{%s} & \textcolor{ink2}{\small %s} \\ \hline"
                    % (i, esc(p["title"]), esc(p["tag"])))
    rows.append(r"\textcolor{gold}{\bfseries$\bigstar$} & \textbf{%s} & \textcolor{ink2}{\small %s} \\ \hline"
                % (esc(B.BONUS["title"]), esc(B.BONUS["tag"])))
    return "\n".join([
        r"{\setlength{\fboxsep}{3mm}\colorbox{navy}{\includegraphics[width=20mm]{%s}}}\par"
        % LOGO_REL,
        r"\vspace{5mm}{\sffamily\small\bfseries\color{accent}\addfontfeature{LetterSpace=28}SYMBULATOR 9}\par",
        r"\vspace{3mm}{\sffamily\fontsize{40}{44}\selectfont\bfseries\color{navy}A Baker's Dozen\par}",
        r"\vspace{5mm}{\color{gold}\rule{38mm}{2.2mm}}\par",
        r"\vspace{4mm}{\sffamily\Large\color{ink2}Twelve solved examples from the documentation, and a bonus\par}",
        r"\vspace{7mm}\begin{minipage}{150mm}\large",
        esc("Each of these circuits looks like an afternoon's work by hand. "
            "Symbulator solves each one in a single run, or in two when a switch "
            "splits the problem into intervals. No two of them make the same point. "
            "Every description below is the one in the app's built-in examples, and "
            "every answer was checked against the app on 16 September 2026. The link "
            "under each run opens the entry in the online app."),
        r"\end{minipage}\par",
        r"\vspace{8mm}{\sffamily\arrayrulecolor{rule}\renewcommand{\arraystretch}{1.55}%",
        r"\begin{tabular}{@{}p{9mm}p{72mm}p{85mm}@{}}\hline",
        *rows,
        r"\end{tabular}}",
    ])


def main():
    body = [PREAMBLE, cover()]
    for i, p in enumerate(B.P, 1):
        body.append(problem(p, f"Sample {i} of 12"))
    body.append(problem(B.BONUS, "Bonus"))
    body.append(r"\end{document}" + "\n")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n\n".join(body))
    print(f"wrote {OUT}")
    if "--pdf" in sys.argv:
        tmp = tempfile.mkdtemp(prefix="bakers_dozen_tex_")
        for _ in range(2):
            r = subprocess.run(["xelatex", "-interaction=nonstopmode", "-halt-on-error",
                                f"-output-directory={tmp}", "bakers_dozen.tex"],
                               cwd=HERE, capture_output=True, text=True,
                               encoding="utf-8", errors="replace")
        log = io.open(os.path.join(tmp, "bakers_dozen.log"), encoding="utf-8",
                      errors="replace").read()
        pdf = os.path.join(tmp, "bakers_dozen.pdf")
        if r.returncode or not os.path.isfile(pdf):
            print(log[-3000:])
            raise SystemExit("xelatex failed; the log tail is above.")
        target = os.path.join(HERE, "bakers_dozen_latex.pdf")
        shutil.copy2(pdf, target)
        warn = [l for l in log.splitlines() if "Overfull" in l or "Missing character" in l]
        print(f"compiled {target}")
        print(f"{len(warn)} overfull-box or missing-character line(s) in the log")
        for l in warn[:20]:
            print("  ", l)
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    main()
